stages:
  download:
    cmd: Rscript R/download.R
    deps:
      - R/download.R
    outs:
      - download
  process:
    cmd: Rscript R/process.R
    deps:
      - R/process.R
      - download
    outs:
      - brick/dbSNP.parquet/