stages:
  download:
    cmd: Rscript R/download.R
    deps:
      - R/download.R
    outs:
      - cache/GCF_000001405.39.gz:
          cache: false
  process:
    cmd: Rscript R/process.R
    deps:
      - R/process.R
      - cache/GCF_000001405.39.gz
    outs:
      - data/dbSNP.parquet